version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: devsu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devsu_db
      MYSQL_USER: devsu_user
      MYSQL_PASSWORD: devsu_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devsu-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:

networks:
  devsu-network:
    driver: bridge
